- hosts: all
  name: Script de test pour semaphore UI
  tasks:
    - name: print du groupe
      ansible.builtin.debug:
        msg: La machine {{ inventory_hostname }} fait partie du groupe {{ group_names }} sur le site {{ site }}

    - name: Envoi de l'image
      ansible.builtin.copy:
        src: funny_cat.jpg
        dest: /home/maxime